"""Train the banana/poop detector used by detector_node.

Reproduces the model in ros2_ws/src/yolo_pf/models/banana_poop.pt:
YOLO11s pretrained on COCO, fine-tuned on training/dataset (generated by generate_dataset.py).

Usage (from the repository root):
    python training/train.py
    cp training/runs/banana_poop/weights/best.pt ros2_ws/src/yolo_pf/models/banana_poop.pt
"""
from pathlib import Path

from ultralytics import YOLO

HERE = Path(__file__).resolve().parent

model = YOLO('yolo11s.pt')          # COCO weights, downloaded automatically
model.train(
    data=str(HERE / 'dataset' / 'data.yaml'),
    imgsz=320,                      # native Kinect resolution (320x240)
    epochs=80,
    batch=32,
    patience=25,
    fliplr=0.5,                     # horizontal flip augmentation
    mosaic=1.0,                     # 4-image mosaic augmentation
    workers=4,
    project=str(HERE / 'runs'),
    name='banana_poop',
    exist_ok=True,
)
metrics = model.val()
print(f'mAP50={metrics.box.map50:.3f}  mAP50-95={metrics.box.map:.3f}')
